### ISSUE TITLE
Unable to link device 

### ISSUE THREAD

**Issue by frankTurtle** [davidrusu/marker.network#1]
It started a week or two ago, I was unable to sync my device. So I de-registered and was going to setup again. I am unable to find the OTC from the remarkable website anymore. Does this relate to their new Connect service? 

* Note the URL in the screenshot
![image](https://user-images.githubusercontent.com/5667044/137194763-d30166d3-795c-42e0-baa9-f84fdc1adc79.png)

**Comment by davidrusu** [comment]
Looks like reMarkable changed their OTC url again, do you mind trying this one instead?

https://my.remarkable.com/device/desktop/connect

If that works, I can push out a release with the new link

**Comment by frankTurtle** [comment]
> 
> 
> Looks like reMarkable changed their OTC url again, do you mind trying this one instead?
> 
> https://my.remarkable.com/device/desktop/connect
> 
> If that works, I can push out a release with the new link

That'll do it 🤙 🙏 I can link it now.

**Comment by davidrusu** [comment]
This is fixed now in v1.5.1, thanks for reporting
