### ISSUE TITLE
Feature request: user defined CSS

### ISSUE THREAD

**Issue by sterlingbaldwin** [davidrusu/marker.network#2]
First, I just came across this project and its great! 

It would be really nice to be able to specify my own CSS so my site looks different then everyone else's. 

Also, I would really like to make the pictures bigger, it seems like there's a ton of empty space next to text that's to small to read very well.

**Comment by davidrusu** [comment]
Hi Sterling, would you mind attaching a screenshot where the pictures are too small?

As for custom CSS, I'm not sure that's the direction I want to go just yet. My concern is with where to focus my limited time. Most people likely are not familiar enough with CSS to use this feature and at the same time I predict it would be the source of a lot of issues in the future as we introduce new features.

There's a bunch of other things I'd like to add first i.e.
1. Allowing users to comment/annotate your notebooks (if you enable it)
2. The ability to place text between pages of a notebook to allow for more narrative pages.
3. Automatic OCR + full text search
etc.

If users can modify CSS, each of these features could break user sites, it would make developing marker.network much more difficult for me.

So perhaps in the future, when things are stable we can start to allow user defined styling.

**Comment by sterlingbaldwin** [comment]
<img width="1552" alt="Screen Shot 2021-11-17 at 15 19 30" src="https://user-images.githubusercontent.com/6477639/142228317-9470b5d9-8795-4c3f-860e-677e174e2579.png">

This is what Im talking about, there's a bunch of white space on the left side of the screen, and then the notes which look great when I read them on the tablet are a bit to small to be easily readable on the site.

**Comment by davidrusu** [comment]
I see, yeah the current layout is resizing the page so that we can always fit 1 whole page on the screen at a time.

This layout is optimized for "art/drawings" in that you want to take in the whole page at once. Where-as when you are reading text, you want to read line-by-line

I'll see what I can do, perhaps we can add button next to the page to zoom in?

**Comment by davidrusu** [comment]
@sterlingbaldwin I've gone ahead and redesigned the generated sites to make text more legible (and polish up a bunch of things too): https://marker.network/@lbSterling/posts/Stochastic-methods/1-11-21.html

Let me know how the new feel is.

Also in the 1.6.0 release is support for templates in the rendered notebooks

**Comment by sterlingbaldwin** [comment]
This is great! Thanks!
