### ISSUE TITLE
Can't register with OTP

### ISSUE THREAD

**Issue by apeixinho** [davidrusu/marker.network#7]
> Attempting to register with OTC:  yhljfxza
> Bad OTC, failed to register
> Something's wrong with that code, please double check it and try again
> 

I've checked the OTP, it's correct copied it from clipboard.
I'm guessing this block of code is no longer functional:

    function attemptToRegister() {
    var oneTimeCode = $("#one-time-code").val();
    console.log("Attempting to register with OTC: ", oneTimeCode);
    electron_1.ipcRenderer.invoke("link-device", oneTimeCode).then(function (resp) {
        $("#register-spinner").empty();
        if (resp.success) {
            console.log("Success!");
            $("#one-time-code").removeClass("input-error");
        }
        else {
            console.log("Bad OTC, failed to register");
            $("#one-time-code").addClass("input-error");
            $("#register-error-msg").text("Something's wrong with that code, please double check it and try again");
        }
    });
    $("#register-error-msg").empty();
    $("#register-spinner").empty();
    $("#register-spinner").append(nice_stuff_1.spinner);
    }

**Comment by davidrusu** [comment]
Hi Apeixinho, unfortunately remarkable changed their API's and I haven't had the time to update, apologies for the inconvenience.
